// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_SURVIVAL);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_SURVIVAL_UNASSIGNED);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_SURVIVAL_TRACKER);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_SURVIVAL_THIRST);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_SURVIVAL_HUNGER);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_SURVIVAL_TEMPERATURE);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_SURVIVAL_ILLNESS);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_SURVIVAL_INJURY);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_SURVIVAL_CONDITIONS);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_SURVIVAL_MENTAL);