// Fill out your copyright notice in the Description page of Project Settings.


#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ACTION_START);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ACTION_TICKING);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ACTION_END);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_STATE_ACTIVE);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_STATE_DEACTIVE);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_STATE_TRANSIENT);